# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      brew_packages: openssl
      latex: false
      r:
        - oldrel
        - release
        - devel
cache: packages
addons:
  apt:
    packages:
      - libssl-dev
r:
  - oldrel
  - release
  - devel
